name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Build Docker, Deploy to Heroku
    runs-on: ubuntu-20.04
    env:
      model-dir: ./app/src/

    steps:
      - name: Checkout repo source code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Download model artifacts
        run: s3:/rapidrabbit76-pretrained-models/Arbitrary-Style-Transfer-in-Real-Time-With-Adaptive-Instance-Normalization-pytorch-lightning/ ./app/src/

      - name: Deployment Heroku container
        uses: jctaveras/heroku-deploy@v3.0.0
        with:
          email: "yslee.dev@gmail.com"
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: "neural-style-transfer-76"
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: "./app"
          process_type: "web"
